Repository newsgm/NewsAddon-GermanMiner-Labymod, pull requests merged in 2022-11, with the labels that each got.

#43 Fixed typo
  src/main/java/dev/janheist/newsaddon/main/SocketConnection.java
Labels: bug, review

#41 Aktuellen Server anzeigen
  src/main/java/dev/janheist/newsaddon/main/SocketConnection.java
Labels: enhancement, good first issue

#40 Klickbare Texte
  src/main/java/dev/janheist/newsaddon/commands/daCommand.java
  src/main/java/dev/janheist/newsaddon/events/onSend.java
  src/main/java/dev/janheist/newsaddon/features/Dauerauftrag.java
  src/main/java/dev/janheist/newsaddon/features/NewsAddonCommand.java
  src/main/java/dev/janheist/newsaddon/main/NewsAddon.java
  src/main/java/dev/janheist/newsaddon/main/SocketConnection.java
  src/main/java/dev/janheist/newsaddon/timer/DauerauftragTimer.java
  src/main/java/dev/janheist/newsaddon/utls/ClickableTexts.java
  src/main/java/dev/janheist/newsaddon/utls/CustomClickEvent.java
  src/main/java/dev/janheist/newsaddon/utls/TickEvent.java
Labels: enhancement
